# Run React Native Mobile App with Expo
# Equipment Reservation System
# Automatically detects active LAN IP, configures Expo Packager Hostname,
# updates mobile/.env, and verifies connectivity.

[CmdletBinding()]
param(
    [switch]$Tunnel,
    [switch]$Clear,
    [switch]$DryRun,
    [string]$Ip
)

$ErrorActionPreference = "Stop"

# Determine directories
$currentDir = Get-Location
if (Test-Path (Join-Path $currentDir "mobile\package.json")) {
    $RootDir = $currentDir
    $MobileDir = Join-Path $currentDir "mobile"
} elseif ((Test-Path (Join-Path $currentDir "package.json")) -and (Test-Path (Join-Path $currentDir "App.tsx"))) {
    $MobileDir = $currentDir
    $RootDir = Split-Path -Parent $currentDir
} else {
    $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    if (Test-Path (Join-Path $ScriptDir "mobile\package.json")) {
        $RootDir = $ScriptDir
        $MobileDir = Join-Path $ScriptDir "mobile"
    } else {
        $RootDir = Split-Path -Parent $ScriptDir
        $MobileDir = $ScriptDir
    }
}

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  Equipment Reservation System - Mobile Client (Expo)"     -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Resolve Target IP Address
$targetIp = $null
$interfaceName = "Manual Override"

if ($Ip) {
    $targetIp = $Ip
    Write-Host "[CONFIG] Using user-specified IP: $targetIp" -ForegroundColor Yellow
} else {
    # Method A: Active default route (the adapter connected to Wi-Fi / LAN router with internet access)
    $activeRoute = Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue |
        Sort-Object RouteMetric | Select-Object -First 1

    if ($activeRoute) {
        $ipObj = Get-NetIPAddress -InterfaceIndex $activeRoute.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object { $_.IPAddress -notmatch '^169\.254\.' -and $_.IPAddress -notmatch '^127\.' } |
            Select-Object -First 1
        if ($ipObj) {
            $targetIp = $ipObj.IPAddress
            $interfaceName = $ipObj.InterfaceAlias
        }
    }

    # Method B: Physical adapters with link Up
    if (-not $targetIp) {
        $adapters = Get-NetAdapter -Physical -ErrorAction SilentlyContinue | Where-Object { $_.Status -eq 'Up' }
        foreach ($adapter in $adapters) {
            $ipObj = Get-NetIPAddress -InterfaceIndex $adapter.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
                Where-Object { $_.IPAddress -notmatch '^169\.254\.' -and $_.IPAddress -notmatch '^127\.' } |
                Select-Object -First 1
            if ($ipObj) {
                $targetIp = $ipObj.IPAddress
                $interfaceName = $adapter.Name
                break
            }
        }
    }

    # Method C: General IPv4 fallback excluding virtual adapters (VirtualBox 192.168.56.x, VMware, Hyper-V)
    if (-not $targetIp) {
        $fallback = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue) |
            Where-Object {
                $_.IPAddress -notmatch '^127\.' -and
                $_.IPAddress -notmatch '^169\.254\.' -and
                $_.IPAddress -notmatch '^192\.168\.56\.' -and
                $_.InterfaceAlias -notmatch 'Virtual' -and
                $_.InterfaceAlias -notmatch 'VMware' -and
                $_.InterfaceAlias -notmatch 'vEthernet'
            } | Select-Object -First 1
        if ($fallback) {
            $targetIp = $fallback.IPAddress
            $interfaceName = $fallback.InterfaceAlias
        }
    }
}

if (-not $targetIp) {
    $targetIp = "127.0.0.1"
    $interfaceName = "Loopback Fallback"
    Write-Host "[WARN] Could not detect LAN IP. Defaulting to 127.0.0.1" -ForegroundColor Yellow
} else {
    Write-Host "[AUTO-DETECT] Network Adapter: $interfaceName" -ForegroundColor Green
    Write-Host "[AUTO-DETECT] Detected LAN IP:  $targetIp" -ForegroundColor Green
}

# 2. Automate Environment Configurations
$apiUrl = "http://${targetIp}:8000/api/v1"
Write-Host "[CONFIG] Backend API URL:      $apiUrl" -ForegroundColor Green

# Set REACT_NATIVE_PACKAGER_HOSTNAME so Metro binds and advertises the real Wi-Fi IP in the QR code
$env:REACT_NATIVE_PACKAGER_HOSTNAME = $targetIp
Write-Host "[CONFIG] PACKAGER HOSTNAME set to: $targetIp" -ForegroundColor Green

# Write mobile/.env
$envFilePath = Join-Path $MobileDir ".env"
$envContent = @"
# Auto-generated by run_mobile.ps1
# Interface: $interfaceName
EXPO_PUBLIC_API_URL=$apiUrl
"@
Set-Content -Path $envFilePath -Value $envContent -Encoding UTF8
Write-Host "[CONFIG] Updated mobile/.env with EXPO_PUBLIC_API_URL" -ForegroundColor Green

# 3. Check Backend Status
Write-Host ""
Write-Host "[CHECK] Verifying Backend Status..." -ForegroundColor Yellow
$backendOk = $false
try {
    $localHealth = Invoke-RestMethod -Uri "http://localhost:8000/api/v1/health" -TimeoutSec 3 -ErrorAction Stop
    $backendOk = $true
    Write-Host "[OK] Backend reachable on localhost: $($localHealth.message)" -ForegroundColor Green
} catch {
    Write-Host "[WARN] Backend not responding on http://localhost:8000" -ForegroundColor Yellow
    Write-Host "       Make sure to run .\run_backend.ps1 in a separate terminal." -ForegroundColor Yellow
}

if ($backendOk -and $targetIp -ne "127.0.0.1") {
    try {
        $lanHealth = Invoke-RestMethod -Uri "http://${targetIp}:8000/api/v1/health" -TimeoutSec 3 -ErrorAction Stop
        Write-Host "[OK] Backend reachable on LAN IP ($targetIp)" -ForegroundColor Green
    } catch {
        Write-Host "[WARN] Backend answered on localhost, but could not be reached via $targetIp" -ForegroundColor Yellow
        Write-Host "       Windows Firewall may be blocking incoming port 8000." -ForegroundColor Yellow
    }
}

# 4. Instructions for Phone Testing
Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  HOW TO CONNECT YOUR PHONE:" -ForegroundColor Cyan
Write-Host "  1. Ensure your phone is connected to the same Wi-Fi: $interfaceName" -ForegroundColor White
Write-Host "  2. Test phone connectivity by opening this in your phone's browser:" -ForegroundColor White
Write-Host "     $apiUrl/health" -ForegroundColor Yellow
Write-Host "     (If it loads JSON, your phone can reach the backend)" -ForegroundColor DarkGray
Write-Host "  3. Open Expo Go on your phone and scan the QR code below." -ForegroundColor White
Write-Host ""
Write-Host "  IF YOU GET 'SOMETHING WENT WRONG' (Router Wi-Fi Isolation):" -ForegroundColor Cyan
Write-Host "     Some Wi-Fi networks block devices from talking to each other." -ForegroundColor DarkGray
Write-Host "     To bypass Wi-Fi blocks, run with the -Tunnel switch:" -ForegroundColor DarkGray
Write-Host "     .\run_mobile.ps1 -Tunnel" -ForegroundColor Yellow
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""

Set-Location $MobileDir

if ($DryRun) {
    Write-Host "[DRY RUN] Configuration completed successfully. Skipping bundler launch." -ForegroundColor Green
    return
}

# 5. Launch Expo Metro Bundler
if ($Tunnel) {
    Write-Host "[MODE] Running Expo in TUNNEL mode (Expo Go)..." -ForegroundColor Magenta
    if ($Clear) {
        npx expo start --go --tunnel -c
    } else {
        npx expo start --go --tunnel
    }
} else {
    Write-Host "[MODE] Running Expo in LAN mode (Host: $targetIp, Expo Go)..." -ForegroundColor Green
    if ($Clear) {
        npx expo start --go -c
    } else {
        npx expo start --go
    }
}
